---
run:
  concurrency: 6
  timeout: 5m
linters:
  disable-all: true
  enable:
    - asasalint
    - bidichk
    - canonicalheader
    - containedctx
    - copyloopvar
    - decorder
    - dupl
    - dupword
    - durationcheck
    - errname
    - fatcontext
    - forcetypeassert
    - gocheckcompilerdirectives
    - gochecksumtype
    - gocritic
    - gofmt
    - goimports
    - gosmopolitan
    - govet
    - grouper
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    - intrange
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nilerr
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - sloglint
    - spancheck
    - staticcheck
    - tagalign
    - tagliatelle
    - tenv
    - testableexamples
    - testifylint
    - typecheck
    - unused
    - usestdlibvars
    - wastedassign
    - zerologlint
    # - asciicheck
    # - bodyclose
    # - contextcheck
    # - cyclop
    # - depguard
    # - dogsled
    # - err113
    # - errcheck
    # - errchkjson
    # - errorlint
    # - exhaustive
    # - exhaustruct
    # - exportloopref
    # - forbidigo
    # - funlen
    # - gci
    # - ginkgolinter
    # - gochecknoglobals
    # - gochecknoinits
    # - gocognit
    # - goconst
    # - gocyclo
    # - godot
    # - godox
    # - gofumpt
    # - goheader
    # - gomoddirectives
    # - gomodguard
    # - goprintffuncname
    # - gosec
    # - gosimple
    # - ireturn
    # - lll
    # - mnd
    # - nestif
    # - nilnil
    # - nlreturn
    # - noctx
    # - nolintlint
    # - nonamedreturns
    # - paralleltest
    # - revive
    # - rowserrcheck
    # - sqlclosecheck
    # - stylecheck
    # - testpackage
    # - thelper
    # - tparallel
    # - unconvert
    # - unparam
    # - varnamelen
    # - whitespace
    # - wrapcheck
    # - wsl
linters-settings:
  staticcheck:
    checks: ["SA1019"]
  gocritic:
    enabled-checks:
      - appendCombine
      - badLock
      - badRegexp
      - badSorting
      - badSyncOnceFunc
      - boolExprSimplify
      - builtinShadow
      - builtinShadowDecl
      - commentedOutCode
      - commentedOutImport
      - deferInLoop
      - deferUnlambda
      - docStub
      - dupImport
      - dynamicFmtString
      - emptyDecl
      - emptyFallthrough
      - equalFold
      - evalOrder
      - exposedSyncMutex
      - externalErrorReassign
      - filepathJoin
      - hexLiteral
      - httpNoBody
      - indexAlloc
      - initClause
      - methodExprCall
      - nestingReduce
      - nilValReturn
      - preferDecodeRune
      - preferFilepathJoin
      - preferFprint
      - preferStringWriter
      - preferWriteByte
      - ptrToRefParam
      - rangeExprCopy
      - rangeValCopy
      - redundantSprint
      - regexpPattern
      - regexpSimplify
      - returnAfterHttpError
      - ruleguard
      - sliceClear
      - sloppyReassign
      - sortSlice
      - sprintfQuotedString
      - sqlQuery
      - stringConcatSimplify
      - stringXbytes
      - stringsCompare
      - syncMapLoadAndDelete
      - timeExprSimplify
      - todoCommentWithoutDetail
      - tooManyResultsChecker
      - truncateCmp
      - typeAssertChain
      - typeDefFirst
      - typeUnparen
      - uncheckedInlineErr
      - unlabelStmt
      - unnecessaryBlock
      - unnecessaryDefer
      - weakCond
      - yodaStyleExpr
      # - emptyStringTest
      # - hugeParam
      # - importShadow
      # - octalLiteral
      # - paramTypeCombine
      # - unnamedResult
      # - whyNoLint
