---
run:
  concurrency: 6
  deadline: 5m
linters:
  disable-all: true
  enable:
    - asasalint
    - bidichk
    - containedctx
    - decorder
    - dupl
    - dupword
    - durationcheck
    - errname
    - execinquery
    - forcetypeassert
    - gocheckcompilerdirectives
    - gochecksumtype
    - gofmt
    - goimports
    - gosmopolitan
    - govet
    - grouper
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nilerr
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - sloglint
    - staticcheck
    - tagalign
    - tagliatelle
    - tenv
    - testableexamples
    - testifylint
    - typecheck
    - unused
    - usestdlibvars
    - wastedassign
    - zerologlint
    # - asciicheck
    # - bodyclose
    # - contextcheck
    # - cyclop
    # - depguard
    # - dogsled
    # - errcheck
    # - errchkjson
    # - errorlint
    # - exhaustive
    # - exhaustruct
    # - exportloopref
    # - forbidigo
    # - funlen
    # - gci
    # - ginkgolinter
    # - gochecknoglobals
    # - gochecknoinits
    # - gocognit
    # - goconst
    # - gocritic
    # - gocyclo
    # - godot
    # - godox
    # - goerr113
    # - gofumpt
    # - goheader
    # - gomnd
    # - gomoddirectives
    # - gomodguard
    # - goprintffuncname
    # - gosec
    # - gosimple
    # - ireturn
    # - lll
    # - nestif
    # - nilnil
    # - nlreturn
    # - noctx
    # - nolintlint
    # - nonamedreturns
    # - paralleltest
    # - revive
    # - rowserrcheck
    # - sqlclosecheck
    # - stylecheck
    # - testpackage
    # - thelper
    # - tparallel
    # - unconvert
    # - unparam
    # - varnamelen
    # - whitespace
    # - wrapcheck
    # - wsl
linters-settings:
  staticcheck:
    checks: ["SA1019"]
  gocritic:
    enabled-checks:
      - appendAssign
      - appendCombine
      - argOrder
      - assignOp
      - badCall
      - badCond
      - badLock
      - badRegexp
      - badSorting
      - boolExprSimplify
      - builtinShadow
      - builtinShadowDecl
      - captLocal
      - caseOrder
      - codegenComment
      - commentFormatting
      - commentedOutCode
      - commentedOutImport
      - defaultCaseOrder
      - deferInLoop
      - deferUnlambda
      - deprecatedComment
      - docStub
      - dupArg
      - dupBranchBody
      - dupCase
      - dupImport
      - dupSubExpr
      - dynamicFmtString
      - elseif
      - emptyDecl
      - emptyFallthrough
      - emptyStringTest
      - equalFold
      - evalOrder
      - exitAfterDefer
      - exposedSyncMutex
      - externalErrorReassign
      - filepathJoin
      - flagDeref
      - flagName
      - hexLiteral
      - httpNoBody
      - hugeParam
      - ifElseChain
      - importShadow
      - indexAlloc
      - initClause
      - mapKey
      - methodExprCall
      - nestingReduce
      - newDeref
      - nilValReturn
      - octalLiteral
      - offBy1
      - paramTypeCombine
      - preferDecodeRune
      - preferFilepathJoin
      - preferFprint
      - preferStringWriter
      - preferWriteByte
      - ptrToRefParam
      - rangeExprCopy
      - rangeValCopy
      - redundantSprint
      - regexpMust
      - regexpPattern
      - regexpSimplify
      - returnAfterHttpError
      - ruleguard
      - singleCaseSwitch
      - sliceClear
      - sloppyLen
      - sloppyReassign
      - sloppyTestFuncName
      - sloppyTypeAssert
      - sortSlice
      - sprintfQuotedString
      - sqlQuery
      - stringConcatSimplify
      - stringXbytes
      - stringsCompare
      - switchTrue
      - syncMapLoadAndDelete
      - timeCmpSimplify
      - timeExprSimplify
      - todoCommentWithoutDetail
      - tooManyResultsChecker
      - truncateCmp
      - typeAssertChain
      - typeDefFirst
      - typeSwitchVar
      - typeUnparen
      - uncheckedInlineErr
      - underef
      - unlabelStmt
      - unlambda
      - unnamedResult
      - unnecessaryBlock
      - unnecessaryDefer
      - unslice
      - valSwap
      - weakCond
      - whyNoLint
      - wrapperFunc
      - yodaStyleExpr
