# See https://cloud.google.com/cloud-build/docs/build-config
# Building multi-arch test images for non-x86 architecture

timeout: 1200s
options:
  substitution_option: ALLOW_LOOSE
steps:
  - name: 'gcr.io/k8s-testimages/gcb-docker-gcloud:v20190906-745fed4'
    entrypoint: make
    env:
    - PROJ_ID=$PROJECT_ID
