name: critest dockershim
on: [push, pull_request]
jobs:
  #
  # Run CRI tests against dockershim
  #
  build-and-critest-dockershim:
    strategy:
      matrix:
        os: [ubuntu-18.04] # TODO: Need to add windows-2019
                           # It was also disabled in travis ci
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go 1.13
        uses: actions/setup-go@v2
        with:
          go-version: '1.15'

      - name: Set Go binary path
        shell: bash
        run: |
          echo "GOPATH=${{ github.workspace }}" >> $GITHUB_ENV
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

      - name: Checkout cri-tools for this commit
        uses: actions/checkout@v2
        with:
          path: ${{github.workspace}}/src/github.com/kubernetes-sigs/cri-tools

      - name: Install docker
        run: |
          hack/install-docker.sh
        working-directory: ${{ github.workspace }}/src/github.com/kubernetes-sigs/cri-tools

      - name: Build cri-tools
        run: |
          make
          sudo -E PATH=$PATH make install
        working-directory: ${{ github.workspace }}/src/github.com/kubernetes-sigs/cri-tools

      - name: Build cri-dockerd
        run: |
          sudo -E PATH=$PATH hack/install-cri-dockerd.sh
        working-directory: ${{ github.workspace }}/src/github.com/kubernetes-sigs/cri-tools

      - name: Run critest
        run: |
          sudo -E PATH=$PATH make install.ginkgo
          sudo -E PATH=$PATH hack/run-dockershim-critest.sh
        working-directory: ${{ github.workspace }}/src/github.com/kubernetes-sigs/cri-tools

      - name: Dump docker logs
        run: |
          mkdir -p ${{ github.workspace }}/logs
          sudo journalctl -eu docker | sudo tee ${{ github.workspace }}/logs/docker.log
          ls -atrl ${{ github.workspace }}/logs

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: logs
          path: logs
